!     ******************************************************************
!     PRINT.FOR
!     Copyright(c) Water Resources 2000
!
!     Created: 12/5/2005 9:47:14 AM
!     Author : Craig Miller
!     Last change: CWM 4/1/2010 11:10:17 AM
!     ******************************************************************

Module PrintStuff
!     INTEGER*4 VARIABLES
use PARAMDIM
      INTEGER (KIND=4) :: NRES,INYR,NHPW,KPS,KCE,NQIN, &
            KPE,KSS,NLND,KBS,IHS(MPP),IHP(MPP), &
            IHB(MPP),IHR(MPP),IHNP(MPP),IHPQX(MPP,5), &
            KSI(MPP),KEI(MPP),NCRP(MLAND),KSE,NYRS, &
            KBE,NQS,KCS,LINE,NEXPO,NUNG,NOUFL,ITERMX, &
            IQTG(MRES,19),IOFQX(MRES,19),IQXAD(MRES,19), &
            ICKIN(MQX),ICKOU(MQX),ITYIN(MQX), &
            ITYOU(MQX),ICKBY(MQX),ITYBY(MQX),ICKGW(MQX),ITYGW(MQX), &
            ICKUP(MQX),ITYUP(MQX),ICKRS(MQX),ITYRS(MQX), &
            NDEML(MLAND,MRES),LMRES(MLAND,MRES),IYEAR(MYEAR),IPQX(MQX), &
            IPAGE,NQX,IQH(MRES),IINFL(19),NINFL,ITRIB(19),NTRIB, &
            IIMP(19),NIMP,IEXPO(19),IUNG(19),IQXN(MQSTA), &
            IREST(MRES),IOFBY(MRES),IOFUP(MRES),IQNUM(MMIN), &
            IQRES(MMIN),IPH(MLAND),IPHU(MLAND),IPHD(MLAND), &
            NQLIN(MLAND),IRV(MLAND),IFT(MLAND),IRT(MLAND), &
            LNRS(MLAND),KI(MPP),KU(MPP),KB(MPP),IHYUP(MPP), &
            ISEPQ(MRES), BEGDEL(MRES,11),ENDDEL(MRES,11), &
            IUR(MLAND),NFDT
!     INTEGER*4 VARIABLES
      INTEGER (KIND=4) :: ITERA
!     REAL*4 VARIABLES
      REAL (KIND=8) :: SHORT(MLAND,MYEAR,13),CPAC(MLAND,MCRPS), &
            CPACFT(MLAND,MYEAR,13),ELV(MRES,MYEAR,13), &
            LGEFPRE(MLAND,13), &
            SAR(MPP,MYEAR,13),HEAD(MPP,MYEAR,13),ENER(MPP,MYEAR,13), &
            WETUSE(13,MYEAR,MLAND),BCS,FNYRS,HPLEN(MPP,5), &
            HPDIA(MPP,5),HPRGH(MPP,5),QPXMI(MPP),QPMNI(MPP), &
            HDMNI(MPP),ELTWI(MPP),E1I(MPP),CPRO(MLAND,MCRPS), &
            PRACFT(MLAND,13),TM(MLAND,13),PR(MLAND,13),QDVR(MLAND,13), &
            WTUS(MLAND,13),CPUS(MLAND,13),QDMI(MLAND,13), &
            QDVRA(MLAND,13),OFMN(MRES,13),QSM(MRES,13),QTG(MRES,13), &
            CONUSE(13,MYEAR,MLAND),HLOSS(MPP,5),WSOIL(MLAND), &
            WMOIS(MLAND),WPRO(MLAND),CPMUL(MLAND),QIN(MQSTA,MYEAR,13), &
            WTACFT(MLAND,MYEAR,13),ACRAG(MLAND),WACRE(MLAND), &
            RETI(MLAND),QDMIY(MLAND),TOTSO(13),STOIC(MRES), &
              HYHD(MPP),WSHOR(13),HYFLMN(MRES,13),LGUSE(MLAND,MYEAR,13), &
              ACRAGR(MLAND),LGQRTF(MLAND),LGQDVA(MLAND), &
              LGPOT(MLAND,MYEAR,13),ESEEP(10,MRES),SSEEP(10,MRES)
!     LOGICAL*1 VARIABLES
      LOGICAL (KIND=1) :: IOFF(MRES),IPST,IPEV,IPEL,IPAS,IPSH,IPSA,IPQIN, &
            IREL(MRES),ISTOR(MRES),PRNRS(MRES),REVAP(MRES),ISTOP, &
              PRNLND(MLAND),SPLOT,LCALEN(MLAND),IPQN(MRES),CALLED(MRES), &
              DRAWN(MRES),SEEPTB(MRES),QMNLMT(MRES)
      REAL (KIND=8) :: QXMN(13,MMIN)
      INTEGER (KIND=4) :: IQXMN(20,MMIN),IDV(MLAND,40), &
            IBY(MLAND,40),ILQIN(MLAND,40),ILUP(MLAND,40), &
            LRES(MLAND,11)
      REAL (KIND=8) :: FBYPS(MLAND,11,13),YIELD(13)
      INTEGER (KIND=4) :: ILNQ(MLAND,MRES,20)
      REAL (KIND=8) :: RELEAS(MRES,MYEAR,13)
      REAL (KIND=8) :: RSTORE(MRES,MYEAR,13)
      REAL (KIND=8) :: RSEVAP(MRES,MYEAR,13)
      REAL (KIND=8) :: WCUSE(MLAND,MYEAR,13)
      REAL (KIND=8) :: CPLOVR(MLAND,21,13)
      REAL (KIND=8) :: WULOVR(MLAND,MRIPA,13),CEFF(MLAND)
      INTEGER (KIND=4) :: IGRND(MLAND,12)
      CHARACTER :: QXNAM(MQX)*75,TITLE*80,DATE2*20,PRESV(MRES)*32, &
           PLAND(MLAND)*32,PHYPW(MPP)*32, &
           VAR(14)*4,QFILE(MQSTA)*40,CDESCR(MQSTA)*31, &
           QINAM(MQSTA)*80,STOFIL(MRES)*80, &
           RELFIL(MRES)*80,EVAFIL(MRES)*80,QXFIL*80
      REAL (KIND=8) :: PCRF(MLAND,10),SSTO(MLAND,11),LGSSTO(MLAND,11)
      REAL (KIND=8) :: PRE(13,MYEAR),TEM(13,MYEAR),CCOEF(MCRPS,13), &
            EFPRE(MLAND),DAYS(12),GWMI(13),EFMIP(MLAND,12),IEFF(MLAND)
      REAL (KIND=8) :: CRID,MOIST(MLAND),SOIL(MLAND),BEGSOL(MLAND)
      REAL (KIND=8) :: CROPS(MCRPS,MYEAR,13),LGEFF(MLAND)
      REAL (KIND=8) :: PERCO(13,MYEAR,MLAND),LPERCO(13,MYEAR,MLAND)
      REAL (KIND=8) :: TDIVR(13),RZ(13),RFLO(13),EFCR(13),RSSP(13), &
       CPCU(13),ACUSM(13),CHSM(13),CUDEF(13),CACU(13),RFGW(13), &
       TOTRF(13),DPUM(13),DSUP(13),DRET(13),DDEF(13),WSUP(13), &
       WPRE(13),WCONS(13),WOPN(13),TOUTF(13),CHGW(13),TGAGE(13), &
       TMUN(13),WPCUM(13),WPCHG(13),BEFP(MLAND),DDIV(13), &
       TSUB(13),RZSUP(13),GWLOS(13),SMSPL(13),GWRTUS(13),STDIF(MRES,13) &
       ,RIVGW(13),TOTLS(13),ADIVR(MLAND,13),ASHOR(MLAND,13), &
              AUSE(MLAND,13),ASOIL(MLAND,13),ARETFL(MLAND,13), &
              LGEFPR(13),LGOUT(13),DMUSE(13),DMACU(13),WTDEP(13), &
              CPDEP(13)
      REAL (KIND=8) :: BUG(30,13),BUGT(30,13)
      CHARACTER :: BUGTITL(30)*20
      REAL (KIND=8) :: AGDEL(MLAND),DMDEL(MLAND),DMPUM(MLAND), &
              DMPUMA(MLAND), &
       AGWAT(MLAND),RETFL(MLAND),SPILL(MLAND),GWRIV(MLAND), &
       RTSOI(MLAND),RTMOI(MLAND),GWQDU(MLAND),QDVA(MLAND), &
       GWMIRT(MLAND),BEFM(MLAND),TEF(MLAND),DEF(MLAND,12), &
       AGDEM(MLAND),DMDEM(MLAND),GWMOI(MLAND),QRTF(MLAND), &
       AGOUT(MLAND), &
       SBSOI(MLAND),SBMOI(MLAND),LGDEL(MLAND),LGRET(MLAND)
      CHARACTER :: CPCODE(MLAND,MCRPS)*6,CPNAM(MLAND,MCRPS)*40 &
            ,LNTYP(MLAND,MCRPS)*13,TMPFIL(MLAND)*80
      REAL (KIND=8) :: RESCAL(MLAND,MRES)
      LOGICAL*1 ISBY(MLAND,10)
      LOGICAL*1 ISOL(MLAND),IRSRED(MRES,3)
END MODULE PrintStuff
